# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: qXx)cYvSHJlRW0{e>uZJG8u
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
    steps:
    - uses: actions/checkout@v3
    - uses: azure/sql-action@v1
      with:
        server-name: 'localhost'
        connection-string: 'Server=localhost,1433;Database=master;Integrated Security=false;User Id=sa;Password=qXx)cYvSHJlRW0{e>uZJG8u;Persist Security Info=True;MultipleActiveResultSets=true;Application Name=DataAccessGeneration'
        sql-file: './DataAccessGeneration.IntegrationTest/Northwind/instnwnd.sql'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test DataAccessGeneration.XUnitTest --no-build --verbosity normal
      
    - name: Integration Test
      run: dotnet test DataAccessGeneration.IntegrationTest --no-build --verbosity normal
  